<?php

/**
 * @file
 * Install and uninstall code for Custom Module.
 *
 * Long description here.
 */


/**
 * Implements hook_install().
 */
function codemirror_ckeditor_install() {

  // Do some things on install, like setting the module weight.

}

/**
 * Implements hook_uninstall().
 */
function codemirror_ckeditor_uninstall() {

  // Do some things on uninstall, like deleting all variables.
}
